// One-time: carry the Vercel Blob store into D1.
//
// Run once, before the switchover, so nothing is lost in the move. What would be lost without
// it is not just a list of old emails — it is every reader fingerprint the tracker has learned.
// Attribution works by recognising a reader it has seen before on a one-to-one message, so an
// empty store means every recipient becomes a stranger again and the panel goes quiet for weeks.
//
// This reads pathnames only, never blob CONTENT, for the same reason the old reader did: every
// fact needed is encoded in the path. That also keeps the migration to three billed list calls
// rather than several thousand fetches.
//
// It writes SQL files rather than talking to D1 itself, so the output can be read before it is
// applied, and applied with the same wrangler command as the schema:
//
//   node migrate/from-blob.mjs
//   npm run migrate:local     # or migrate:remote
//
// The output is SPLIT ACROSS NUMBERED FILES, which is not tidiness. `wrangler d1 execute
// --file` sends the file as a single payload and D1 rejects anything over 100 KB with
// `statement too long: SQLITE_TOOBIG` — the whole history is ~930 KB, so one file fails no
// matter how short the individual statements are (the longest here is 762 bytes). Chunks are
// capped well under the limit and applied in order.
//
// Re-running is safe: every statement is an idempotent upsert or an INSERT guarded by NOT
// EXISTS, so a half-finished run can simply be run again.

import { readFileSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { parseMessagePath, parseEventPath } from '../lib/paths.js';

const API = 'https://blob.vercel-storage.com';

function token() {
  // Read from the environment first; fall back to the file `vercel env pull` writes.
  if (process.env.BLOB_READ_WRITE_TOKEN) return process.env.BLOB_READ_WRITE_TOKEN;
  for (const f of ['.env.vercel', '.env.local']) {
    try {
      const m = /^BLOB_READ_WRITE_TOKEN="?([^"\n]+)"?/m.exec(readFileSync(f, 'utf8'));
      if (m) return m[1];
    } catch { /* not there; try the next one */ }
  }
  throw new Error('BLOB_READ_WRITE_TOKEN is not set. Run: npx vercel env pull .env.vercel --environment=production');
}

/**
 * Every blob under a prefix, following pagination.
 *
 * The prefix is required, not optional — the API answers a prefix-less list with 400. That is
 * why this walks the three known prefixes rather than asking for everything at once.
 */
async function list(prefix, tok) {
  const out = [];
  let cursor;
  do {
    const url = new URL(API);
    url.searchParams.set('prefix', prefix);
    url.searchParams.set('limit', '1000');
    if (cursor) url.searchParams.set('cursor', cursor);
    const res = await fetch(url, { headers: { authorization: `Bearer ${tok}`, 'x-api-version': '7' } });
    if (!res.ok) throw new Error(`blob list ${prefix} → ${res.status}: ${await res.text()}`);
    const body = await res.json();
    out.push(...(body.blobs || []));
    cursor = body.hasMore ? body.cursor : null;
  } while (cursor);
  return out;
}

const q = (v) => (v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => String(Number(v) || 0);

const say = (...a) => console.error(...a);   // progress on stderr, SQL on stdout

const tok = token();
say('Reading the Blob store…');

const [msgBlobs, evBlobs, selfBlobs] = await Promise.all([
  list('msg/', tok), list('ev/', tok), list('self/', tok),
]);
say(`  msg/  ${msgBlobs.length}`);
say(`  ev/   ${evBlobs.length}`);
say(`  self/ ${selfBlobs.length}`);

const lines = [];
lines.push('-- Generated by migrate/from-blob.mjs. Safe to re-run.');
lines.push('');

// ── messages ────────────────────────────────────────────────────────────────────────────────
//
// A token can own several blobs: an amend wrote a second record rather than replacing the
// first. Collapsing them here uses the same rule the old reader used at query time — a non-empty
// value beats an empty one, a larger stated audience beats a smaller one — and keeps the
// EARLIEST upload as the send time, because that is when the message actually went out.
const byToken = new Map();
const skipped = [];
for (const b of msgBlobs) {
  const m = parseMessagePath(b.pathname);
  // Named, never counted silently.
  //
  // The one real case in the live store is a registration written before the empty-segment fix
  // in lib/paths.js: a message with no recipient AND no subject put two slashes side by side,
  // the store collapsed them, and the path came back five segments long instead of seven. Such
  // a record carries no recipient, no subject and nothing to attribute, so it is dropped rather
  // than guessed at — but it is printed, so "dropped" is a decision on the record and not an
  // accident.
  if (!m) { skipped.push(b.pathname); continue; }
  const rec = { ...m, registeredAt: b.uploadedAt };
  const prev = byToken.get(m.token);
  if (!prev) { byToken.set(m.token, rec); continue; }
  byToken.set(m.token, {
    ...prev,
    recipient: rec.recipient || prev.recipient,
    subject: rec.subject || prev.subject,
    source: rec.source && rec.source !== 'unknown' ? rec.source : prev.source,
    recipientCount: Math.max(prev.recipientCount || 0, rec.recipientCount || 0),
    registeredAt: prev.registeredAt < rec.registeredAt ? prev.registeredAt : rec.registeredAt,
  });
}

for (const m of byToken.values()) {
  lines.push(
    `INSERT INTO messages (token, day, recipient, recipients_json, subject, source, recipient_count, registered_at, self_tag, links_json) VALUES (` +
    `${q(m.token)}, ${q(m.day)}, ${q(m.recipient)}, NULL, ${q(m.subject)}, ${q(m.source)}, ${n(m.recipientCount)}, ${q(m.registeredAt)}, '', '[]')` +
    ` ON CONFLICT(token) DO UPDATE SET` +
    ` recipient = CASE WHEN excluded.recipient != '' THEN excluded.recipient ELSE messages.recipient END,` +
    ` subject = CASE WHEN excluded.subject != '' THEN excluded.subject ELSE messages.subject END,` +
    ` recipient_count = MAX(messages.recipient_count, excluded.recipient_count),` +
    ` registered_at = MIN(messages.registered_at, excluded.registered_at);`,
  );
}

// ── events ──────────────────────────────────────────────────────────────────────────────────
//
// Guarded by NOT EXISTS on the natural key rather than a UNIQUE constraint, because two genuine
// opens by the same reader in the same second are possible and the live table must keep both.
// The guard exists only so re-running this migration cannot double the history.
let unparsedEv = 0;
let orphanEv = 0;
for (const b of evBlobs) {
  const e = parseEventPath(b.pathname);
  if (!e) { unparsedEv++; continue; }
  if (!byToken.has(e.token)) orphanEv++;
  const at = preciseAt(b.pathname) || e.at;
  lines.push(
    `INSERT INTO events (token, at, kind, classification, fingerprint, device, destination, device_hint) ` +
    `SELECT ${q(e.token)}, ${q(at)}, ${q(e.kind)}, ${q(e.classification)}, ${q(e.fingerprint)}, ${q(e.device)}, NULL, NULL ` +
    `WHERE NOT EXISTS (SELECT 1 FROM events WHERE token = ${q(e.token)} AND at = ${q(at)} AND kind = ${q(e.kind)} ` +
    `AND COALESCE(fingerprint,'') = COALESCE(${q(e.fingerprint)},''));`,
  );
}

/**
 * The event's time to the millisecond, read back out of the blob's filename.
 *
 * This exists because of a bug this migration nearly shipped. `parseEventPath` deliberately
 * truncates to whole seconds, which is fine for reading but wrong as a de-duplication key: the
 * filenames carry milliseconds, and a reader whose client fetches the pixel twice half a second
 * apart writes two genuinely distinct events inside the same second. Keyed on seconds, 47 real
 * rows — 41 of them human opens, about 8% of the open history — collapsed into their neighbours
 * and the open counts would have quietly dropped in the move.
 *
 * Full precision also matches what the live handlers now write, since `new Date().toISOString()`
 * has always included milliseconds, so old and new rows end up in the same format.
 *
 * Filename stamp: YYYYMMDDTHHMMSSmmmZ — an ISO timestamp with its punctuation stripped.
 */
function preciseAt(pathname) {
  const m = /\/(\d{8})T(\d{6})(\d{3})Z__/.exec(pathname);
  if (!m) return null;
  const [, d, t, ms] = m;
  return `${d.slice(0, 4)}-${d.slice(4, 6)}-${d.slice(6, 8)}T${t.slice(0, 2)}:${t.slice(2, 4)}:${t.slice(4, 6)}.${ms}Z`;
}

// ── self IPs ────────────────────────────────────────────────────────────────────────────────
let unparsedSelf = 0;
for (const b of selfBlobs) {
  const m = /^self\/([0-9a-f]{24})\.json$/.exec(b.pathname);
  if (!m) { unparsedSelf++; continue; }
  lines.push(
    `INSERT INTO self_ips (hash, first_seen) VALUES (${q(m[1])}, ${q(b.uploadedAt)}) ON CONFLICT(hash) DO NOTHING;`,
  );
}

// D1 rejects a payload over 100 KB. 60 KB leaves generous headroom without producing hundreds
// of files.
const CHUNK_BYTES = 60_000;
const OUT = 'migrate/data';

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

let chunk = [];
let bytes = 0;
let fileNo = 0;
const flush = () => {
  if (!chunk.length) return;
  fileNo += 1;
  writeFileSync(`${OUT}/${String(fileNo).padStart(3, '0')}.sql`, chunk.join('\n') + '\n');
  chunk = [];
  bytes = 0;
};
for (const line of lines) {
  if (bytes + line.length > CHUNK_BYTES) flush();
  chunk.push(line);
  bytes += line.length + 1;
}
flush();

say('');
say(`Wrote ${fileNo} chunk(s) to ${OUT}/`);
say(`Messages  : ${byToken.size} rows from ${msgBlobs.length} blobs (${msgBlobs.length - byToken.size - skipped.length} amends folded in)`);
say(`Events    : ${evBlobs.length - unparsedEv} rows` + (orphanEv ? `, ${orphanEv} whose message no longer exists` : ''));
say(`Self IPs  : ${selfBlobs.length - unparsedSelf} rows`);
say(`SQL statements: ${lines.length - 2}`);
if (skipped.length) {
  say('');
  say(`SKIPPED ${skipped.length} message blob(s) whose path could not be read:`);
  for (const p of skipped) say(`  ${p}`);
}
if (unparsedEv || unparsedSelf) {
  say(`UNPARSED  : ev ${unparsedEv}, self ${unparsedSelf}  ← inspect before applying`);
}
